'use client';

import { useEffect, useState } from 'react';
import { useAuth, useNavigation } from '@/store';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  ArrowLeft,
  FileText,
  Plus,
  Clock,
  DollarSign,
  MapPin,
  Calendar,
  Loader2,
  ExternalLink,
  FileCode2,
  FileCheck,
  FileSpreadsheet,
} from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';

const docTypes = [
  { value: 'SRS', label: 'SRS', icon: FileText, desc: 'Software Requirements Specification' },
  { value: 'SAD', label: 'SAD', icon: FileCode2, desc: 'Software Architecture Document' },
  { value: 'SDD', label: 'SDD', icon: FileSpreadsheet, desc: 'Software Design Document' },
  { value: 'PRD', label: 'PRD', icon: FileCheck, desc: 'Product Requirements Document' },
  { value: 'BRD', label: 'BRD', icon: FileText, desc: 'Business Requirements Document' },
  { value: 'STD', label: 'STD', icon: FileText, desc: 'System Test Document' },
  { value: 'TRD', label: 'TRD', icon: FileCode2, desc: 'Technical Requirements Document' },
  { value: 'ADR', label: 'ADR', icon: FileText, desc: 'Architecture Decision Record' },
];

export function ProjectDetailView() {
  const { token } = useAuth();
  const { selectedProjectId, navigate } = useNavigation();
  const [project, setProject] = useState<any>(null);
  const [documents, setDocuments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [creatingDoc, setCreatingDoc] = useState<string | null>(null);

  useEffect(() => {
    const fetchProject = async () => {
      if (!selectedProjectId) return;
      setLoading(true);
      try {
        const res = await fetch(`/api/projects/${selectedProjectId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (!res.ok) throw new Error('Failed to fetch project');
        setProject(data.data.project);
        setDocuments(data.data.project.documents || []);
      } catch {
        toast.error('Failed to load project');
        navigate('projects');
      } finally {
        setLoading(false);
      }
    };
    if (selectedProjectId && token) fetchProject();
  }, [selectedProjectId, token, navigate]);

  const handleCreateDoc = async (type: string) => {
    if (!selectedProjectId) return;
    setCreatingDoc(type);
    try {
      const res = await fetch('/api/documents', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: selectedProjectId,
          type,
          title: `${project?.name || 'Project'} - ${type}`,
          content: `# ${type} Document\n\nThis is the ${type} document for "${project?.name}".\n\nGenerated by Espacify on ${format(new Date(), 'PPPP')}.`,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error?.message || 'Failed to create');
      setDocuments((prev) => [data.data.document, ...prev]);
      toast.success(`${type} document created`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to create document');
    } finally {
      setCreatingDoc(null);
    }
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-64" />
        <Skeleton className="h-4 w-96" />
        <div className="grid gap-4 md:grid-cols-3">
          <Skeleton className="h-32" />
          <Skeleton className="h-32" />
          <Skeleton className="h-32" />
        </div>
        <Skeleton className="h-64" />
      </div>
    );
  }

  if (!project) return null;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start gap-3">
        <Button variant="ghost" size="icon" onClick={() => navigate('projects')} className="mt-1">
          <ArrowLeft className="w-5 h-5" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h1 className="text-2xl font-bold tracking-tight">{project.name}</h1>
            <Badge variant="secondary">{project.status}</Badge>
          </div>
          {project.description && (
            <p className="text-muted-foreground mt-1">{project.description}</p>
          )}
          <div className="flex items-center gap-4 text-xs text-muted-foreground mt-2">
            <span className="flex items-center gap-1"><MapPin className="w-3 h-3" />{project.domain}</span>
            <span className="flex items-center gap-1"><Calendar className="w-3 h-3" />{format(new Date(project.createdAt), 'MMM d, yyyy')}</span>
            {project.budget && (
              <span className="flex items-center gap-1"><DollarSign className="w-3 h-3" />${project.budget.toLocaleString()}</span>
            )}
          </div>
        </div>
      </div>

      {/* Overview Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Documents</p>
                <p className="text-2xl font-bold">{documents.length}</p>
              </div>
              <FileText className="w-8 h-8 text-primary/60" />
            </div>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Status</p>
                <p className="text-2xl font-bold">{project.status}</p>
              </div>
              <Clock className="w-8 h-8 text-primary/60" />
            </div>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Budget</p>
                <p className="text-2xl font-bold">
                  {project.budget ? `$${project.budget.toLocaleString()}` : 'Not set'}
                </p>
              </div>
              <DollarSign className="w-8 h-8 text-primary/60" />
            </div>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Last Updated</p>
                <p className="text-2xl font-bold text-sm">{format(new Date(project.updatedAt), 'MMM d')}</p>
              </div>
              <Calendar className="w-8 h-8 text-primary/60" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Documents */}
      <Tabs defaultValue="documents" className="space-y-4">
        <TabsList>
          <TabsTrigger value="documents" className="gap-1">
            <FileText className="w-4 h-4" /> Documents
          </TabsTrigger>
          <TabsTrigger value="create" className="gap-1">
            <Plus className="w-4 h-4" /> Generate
          </TabsTrigger>
        </TabsList>

        <TabsContent value="documents">
          {documents.length === 0 ? (
            <Card className="border-0 shadow-sm">
              <CardContent className="flex flex-col items-center justify-center py-12 text-center">
                <FileText className="w-12 h-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold mb-1">No documents yet</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Generate specification documents for your project
                </p>
                <Button onClick={() => {}} className="gap-2" disabled>
                  <Plus className="w-4 h-4" /> Generate Documents
                </Button>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {documents.map((doc: any) => (
                <Card key={doc.id} className="border-0 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader className="pb-2">
                    <div className="flex items-start justify-between">
                      <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                          <FileText className="w-4 h-4 text-primary" />
                        </div>
                        <div>
                          <CardTitle className="text-sm font-semibold">{doc.type}</CardTitle>
                          <CardDescription className="text-xs">v{doc.version}</CardDescription>
                        </div>
                      </div>
                      <Badge variant="secondary" className="text-xs">{doc.status}</Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <p className="text-xs text-muted-foreground line-clamp-2 mb-3">{doc.title}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted-foreground">
                        {format(new Date(doc.updatedAt), 'MMM d, yyyy')}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="create">
          <Card className="border-0 shadow-sm">
            <CardHeader>
              <CardTitle className="text-lg">Generate Documents</CardTitle>
              <CardDescription>
                Select document types to generate for your project
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-3 sm:grid-cols-2">
                {docTypes.map((dt) => {
                  const exists = documents.some((d: any) => d.type === dt.value);
                  return (
                    <Button
                      key={dt.value}
                      variant={exists ? 'secondary' : 'outline'}
                      className={cn(
                        'h-auto py-3 px-4 justify-start gap-3',
                        exists && 'opacity-60'
                      )}
                      disabled={exists || creatingDoc === dt.value}
                      onClick={() => handleCreateDoc(dt.value)}
                    >
                      {creatingDoc === dt.value ? (
                        <Loader2 className="w-5 h-5 animate-spin" />
                      ) : (
                        <dt.icon className="w-5 h-5 text-primary" />
                      )}
                      <div className="text-left">
                        <div className="font-medium text-sm">{dt.label}</div>
                        <div className="text-xs text-muted-foreground">{dt.desc}</div>
                      </div>
                      {exists && <Badge variant="outline" className="ml-auto text-xs">Done</Badge>}
                    </Button>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
